feat!: remove default Schnorr functionality
tari-project/tari-crypto pull request #180
Opened 2023-05-24 16:44 UTC by AaronFeickert

Removes default Schnorr signature functionality by requiring domain separation. Closes #178.

This is unfinished, because WASM still exposes signing and verification functions that use the default separation behavior. There's no good reason to do this, as any use of signatures in practice should specify a context-specific separator.

BREAKING CHANGE: Changes the `SchnorrSignature` type to require a generic domain type. Removes `RistrettoSchnorrWithDomain` and replaces `RistrettoSchnorr` with a generic `RistrettoSchnorr<H>`. Removes an unsafe utility signing function.

2023-05-26 05:51 UTC, hansieodendaal approved these changes
I think the changes are good, and agree that the domain should be enforced. I just have some nits about the readability in the test examples, shown below.

ACK

2023-05-26 05:51 UTC, hansieodendaal commented on src/ristretto/ristretto_sig.rs
> +/// let sig: RistrettoSchnorr<ExampleDomain> = SchnorrSignature::sign_message(&k, msg).unwrap();
```suggestion
/// let sig = RistrettoSchnorr::<ExampleDomain>::sign_message(&k, msg).unwrap();
```

2023-05-26 05:51 UTC, hansieodendaal commented on src/ristretto/ristretto_sig.rs
> +        let sig: RistrettoSchnorr<TestDomain> = RistrettoSchnorr::default();
```suggestion
        let sig = RistrettoSchnorr::<TestDomain>::default();
```

2023-05-26 05:51 UTC, hansieodendaal commented on src/ristretto/ristretto_sig.rs
> +        let sig: RistrettoSchnorr<TestDomain> = RistrettoSchnorr::sign_raw(&k, r, &e).unwrap();
```suggestion
        let sig = RistrettoSchnorr::<TestDomain>::sign_raw(&k, r, &e).unwrap();
```

2023-05-26 05:51 UTC, hansieodendaal commented on src/ristretto/ristretto_sig.rs
> +        let s2: RistrettoSchnorr<TestDomain> = RistrettoSchnorr::sign_raw(&k2, r2, &e).unwrap();
```suggestion
        let s1 = RistrettoSchnorr::<TestDomain>::sign_raw(&k1, r1, &e).unwrap();
        let s2 = RistrettoSchnorr::<TestDomain>::sign_raw(&k2, r2, &e).unwrap();

```

2023-05-26 05:51 UTC, hansieodendaal commented on src/ristretto/ristretto_sig.rs
> +        let sig: RistrettoSchnorr<TestDomain> = RistrettoSchnorr::sign_message(&k, msg).unwrap();
```suggestion
        let sig = RistrettoSchnorr::<TestDomain>::sign_message(&k, msg).unwrap();
```

2023-05-26 05:51 UTC, hansieodendaal commented on src/ristretto/ristretto_sig.rs
> +///
```suggestion
/// type RistrettoSchnorr<H> = SchnorrSignature<RistrettoPublicKey, RistrettoSecretKey, H>;
///
```

2023-05-26 05:51 UTC, hansieodendaal commented on src/ristretto/ristretto_sig.rs
>  ///
```suggestion
/// type RistrettoSchnorr<H> = SchnorrSignature<RistrettoPublicKey, RistrettoSecretKey, H>;
///
```

2023-05-26 05:51 UTC, hansieodendaal commented on src/ristretto/ristretto_sig.rs
> +/// let sig: RistrettoSchnorr<ExampleDomain> = RistrettoSchnorr::sign_message(&k, &msg).unwrap();
```suggestion
/// let sig = RistrettoSchnorr::<ExampleDomain>::sign_message(&k, &msg).unwrap();
```

2023-05-26 11:31 UTC, CjS77 commented
I disagree here. As mentioned out in #178, I feel that API ergonomics is important. Newcomers to the library are going to be confused with an API requiring Domain separation and will use a default anyway. Those looking for it will see it in the function signature and will be able to provide their own domains.

2023-05-26 11:31 UTC, CjS77 commented
A lot of tests have been removed -- is there a reason for the decrease in coverage?

2023-05-26 11:32 UTC, CjS77 requested changes
Need consensus before this can be merged.

2023-05-27 02:35 UTC, AaronFeickert commented
> I disagree here. As mentioned out in #178, I feel that API ergonomics is important. Newcomers to the library are going to be confused with an API requiring Domain separation and will use a default anyway. Those looking for it will see it in the function signature and will be able to provide their own domains.

I think implementation snafus like [this](https://github.com/tari-project/tari/pull/5400) are indicative of the risk of providing "a Schnorr signature". The implementer is always free to ignore the recommendation of distinct domain separation, but this API change at least forces them to make a decision. Coupled with the fact that there is no "default" signature by any common standard, I think it's an annoyance whose safety benefit outweighs the inconvenience.

I understand where you're coming from, but respectfully disagree with the conclusion. Frankly, an implementer who is confused by domain separation should probably take a moment to investigate first.

2023-05-27 02:38 UTC, AaronFeickert commented
> A lot of tests have been removed -- is there a reason for the decrease in coverage?

Some were specific to FFI or WASM, and naturally went away. An "invalid scalar" test didn't really make sense, and was nixed. A couple of other tests dealt specifically with the default separator, and are no longer relevant or were modified accordingly.

2023-05-27 02:40 UTC, AaronFeickert commented
One point to keep in mind is that "raw" signatures, in which the caller is responsible for challenge generation, have no inherent notion of domain separation. Currently, it's probably easiest simply to use the default separator type, since it plays no role in generating the Fiat-Shamir challenge. These are used (for good reason) in several places within the `tari` codebase,

2024-03-23 20:03 UTC, closed without merging